# Generated by Django 5.2.8 on 2026-02-17 07:55

import django.core.validators
import django.db.models.deletion
import optimization.validators
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Municipality',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('hq_latitude', models.FloatField(blank=True, null=True, validators=[optimization.validators.validate_damascus_latitude])),
                ('hq_longitude', models.FloatField(blank=True, null=True, validators=[optimization.validators.validate_damascus_longitude])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_municipalities', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Landfill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[optimization.validators.validate_damascus_latitude])),
                ('longitude', models.FloatField(validators=[optimization.validators.validate_damascus_longitude])),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_landfills', to=settings.AUTH_USER_MODEL)),
                ('municipalities', models.ManyToManyField(blank=True, related_name='landfills', to='optimization.municipality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Bin',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('latitude', models.FloatField(validators=[optimization.validators.validate_damascus_latitude])),
                ('longitude', models.FloatField(validators=[optimization.validators.validate_damascus_longitude])),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_bins', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='bins', to='optimization.municipality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Scenario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=255)),
                ('description', models.TextField(blank=True)),
                ('start_latitude', models.FloatField(blank=True, null=True, validators=[optimization.validators.validate_damascus_latitude])),
                ('start_longitude', models.FloatField(blank=True, null=True, validators=[optimization.validators.validate_damascus_longitude])),
                ('collection_date', models.DateField()),
                ('status', models.CharField(choices=[('pending', 'معلقة'), ('in_progress', 'قيد الانجاز'), ('completed', 'منجزة')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bins', models.ManyToManyField(related_name='scenarios', to='optimization.bin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenarios', to=settings.AUTH_USER_MODEL)),
                ('end_landfill', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='ending_scenarios', to='optimization.landfill')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenarios', to='optimization.municipality')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RouteSolution',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('total_distance', models.FloatField(validators=[django.core.validators.MinValueValidator(0.0)])),
                ('data', models.JSONField()),
                ('scenario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='solutions', to='optimization.scenario')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ScenarioTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('weekdays', models.CharField(help_text='Comma separated weekdays numbers where Monday=0 and Sunday=6', max_length=20)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bins', models.ManyToManyField(related_name='scenario_templates', to='optimization.bin')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scenario_templates', to=settings.AUTH_USER_MODEL)),
                ('end_landfill', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_templates', to='optimization.landfill')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scenario_templates', to='optimization.municipality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scenario',
            name='generated_from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='generated_scenarios', to='optimization.scenariotemplate'),
        ),
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('capacity', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_vehicles', to=settings.AUTH_USER_MODEL)),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='vehicles', to='optimization.municipality')),
            ],
            options={
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='scenariotemplate',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenario_templates', to='optimization.vehicle'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='vehicle',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scenarios', to='optimization.vehicle'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['is_active'], name='optimizatio_is_acti_dce822_idx'),
        ),
        migrations.AddIndex(
            model_name='bin',
            index=models.Index(fields=['latitude', 'longitude'], name='optimizatio_latitud_8dca4f_idx'),
        ),
        migrations.AddIndex(
            model_name='routesolution',
            index=models.Index(fields=['scenario', '-created_at'], name='optimizatio_scenari_623069_idx'),
        ),
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['collection_date'], name='optimizatio_collect_ff9540_idx'),
        ),
    ]
