# Generated by Django 5.2.8 on 2026-02-17 16:27

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scenario',
            name='generated_from_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='generated_scenarios', to='optimization.scenariotemplate'),
        ),
    ]
