# Generated by Django 5.2.8 on 2026-03-13 21:49

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bin',
            name='capacity',
            field=models.PositiveIntegerField(choices=[(240, '240 L'), (660, '660 L'), (1100, '1100 L')], validators=[django.core.validators.MinValueValidator(1)]),
        ),
        migrations.AlterField(
            model_name='vehicle',
            name='capacity',
            field=models.PositiveIntegerField(choices=[(5000, '5000 L'), (15000, '15000 L')], validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
