# Generated by Django 5.2.8 on 2026-01-04 16:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0002_alter_scenario_created_by'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddIndex(
            model_name='scenario',
            index=models.Index(fields=['collection_date'], name='optimizatio_collect_ff9540_idx'),
        ),
    ]
