# Generated by Django 5.2.8 on 2026-03-22 10:23

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0002_alter_bin_capacity_alter_vehicle_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='pickup_window_end',
            field=models.TimeField(blank=True, help_text='نهاية نافذة الاستلام', null=True),
        ),
        migrations.AddField(
            model_name='bin',
            name='pickup_window_start',
            field=models.TimeField(blank=True, help_text='بداية نافذة الاستلام', null=True),
        ),
        migrations.AddField(
            model_name='routesolution',
            name='co2_kg',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='routesolution',
            name='total_time',
            field=models.FloatField(default=0.0, validators=[django.core.validators.MinValueValidator(0.0)]),
        ),
        migrations.AddField(
            model_name='scenario',
            name='avoid_streets',
            field=models.TextField(blank=True, default='', help_text='شوارع يجب تجنبها (مفصولة بفاصلة)'),
        ),
        migrations.AddField(
            model_name='scenario',
            name='use_traffic_profile',
            field=models.BooleanField(default=False, help_text='استخدام ملف مروري'),
        ),
    ]
