# Generated by Django 5.2.8 on 2026-03-22 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0003_bin_pickup_window_end_bin_pickup_window_start_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='scenariotemplate',
            name='avoid_streets',
            field=models.TextField(blank=True, default=''),
        ),
        migrations.AddField(
            model_name='scenariotemplate',
            name='use_traffic_profile',
            field=models.BooleanField(default=False),
        ),
    ]
