# Generated by Django 5.2.8 on 2026-02-17 07:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0004_bin_created_by_landfill_created_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='landfill',
            name='description',
        ),
        migrations.RemoveField(
            model_name='municipality',
            name='description',
        ),
    ]
