# Generated by Django 5.2.8 on 2026-03-22 13:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0004_scenariotemplate_avoid_streets_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='bin',
            name='address',
            field=models.CharField(blank=True, help_text='العنوان أو الوصف', max_length=500, null=True),
        ),
    ]
