# Generated by Django 5.2.8 on 2026-03-22 13:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('optimization', '0005_bin_address'),
    ]

    operations = [
        migrations.AddField(
            model_name='landfill',
            name='address',
            field=models.CharField(blank=True, help_text='العنوان أو الوصف', max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='municipality',
            name='address',
            field=models.CharField(blank=True, help_text='العنوان أو الوصف', max_length=500, null=True),
        ),
    ]
