# Generated by Django 5.2.8 on 2025-11-25 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('driver', 'Driver'), ('analyst', 'Analyst'), ('planner', 'Planner'), ('admin', 'Admin')], default='driver', max_length=20),
        ),
    ]
