# Generated by Django 5.2.8 on 2025-12-02 13:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_alter_user_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='purpose',
            field=models.CharField(choices=[('activation', 'Activation'), ('password_reset', 'Password Reset'), ('initial_setup', 'Initial Setup')], max_length=20),
        ),
        migrations.AlterField(
            model_name='user',
            name='last_password_change_reason',
            field=models.CharField(blank=True, choices=[('forgot', 'Forgot'), ('profile', 'Profile'), ('initial_setup', 'Initial Setup')], max_length=20, null=True),
        ),
    ]
