# Generated by Django 5.2.8 on 2025-12-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_onetimepassword_purpose_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_archived',
            field=models.BooleanField(default=False),
        ),
    ]
