# Generated by Django 5.2.8 on 2025-12-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_user_is_archived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='purpose',
            field=models.CharField(choices=[('password_reset', 'Password Reset'), ('initial_setup', 'Initial Setup')], max_length=20),
        ),
    ]
