# Generated by Django 5.2.8 on 2026-03-03 15:28

import django.contrib.gis.db.models.fields
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('optimization', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeviceFingerprint',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('device_id', models.CharField(max_length=255, unique=True)),
                ('ip_address', models.GenericIPAddressField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('last_report_at', models.DateTimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', django.contrib.gis.db.models.fields.PointField(geography=True, srid=4326)),
                ('description', models.TextField(blank=True)),
                ('issue_type', models.CharField(choices=[('container_full', 'Container Full'), ('no_container', 'No Container')], default='container_full', max_length=20)),
                ('urgency_score', models.IntegerField(default=1)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('resolved', 'Resolved'), ('plan_created', 'Immediate Plan Created'), ('bin_requested', 'Bin Requested')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('assigned_scenario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reports', to='optimization.scenario')),
                ('devices', models.ManyToManyField(related_name='reports', to='reports.devicefingerprint')),
                ('municipality', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='citizen_reports', to='optimization.municipality')),
            ],
            options={
                'ordering': ['-urgency_score', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BinRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_type', models.CharField(choices=[('new_bin', 'Create New Bin'), ('resize_bin', 'Resize/Change Existing Bin')], max_length=20)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20)),
                ('note', models.TextField(blank=True, help_text='Planner note or Admin rejection reason')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admin', models.ForeignKey(blank=True, limit_choices_to={'role': 'admin'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='handled_bin_requests', to=settings.AUTH_USER_MODEL)),
                ('planner', models.ForeignKey(limit_choices_to={'role': 'planner'}, on_delete=django.db.models.deletion.CASCADE, related_name='created_bin_requests', to=settings.AUTH_USER_MODEL)),
                ('target_bin', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='resize_requests', to='optimization.bin')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='bin_requests', to='reports.report')),
            ],
        ),
        migrations.CreateModel(
            name='ReportMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='reports/')),
                ('description', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('device', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='reports.devicefingerprint')),
                ('report', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media', to='reports.report')),
            ],
        ),
    ]
