# Generated by Django 5.2.8 on 2026-03-05 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='binrequest',
            name='requested_capacity',
            field=models.PositiveIntegerField(blank=True, help_text='Requested size/capacity', null=True),
        ),
    ]
