# Generated by Django 5.2.8 on 2026-03-05 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0002_binrequest_requested_capacity'),
    ]

    operations = [
        migrations.AlterField(
            model_name='report',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('processed', 'Processed')], default='pending', max_length=20),
        ),
    ]
