# Generated by Django 5.2.8 on 2026-03-13 21:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reports', '0003_alter_report_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='binrequest',
            name='requested_capacity',
            field=models.PositiveIntegerField(blank=True, choices=[(240, '240 L'), (660, '660 L'), (1100, '1100 L')], help_text='Requested size/capacity', null=True),
        ),
    ]
